<?php

namespace GescomBundle\Repository;

/**
 * Product_SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_SupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
