<?php

namespace GescomBundle\Repository;

/**
 * Produt_SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produt_SupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
