<?php

namespace AppBundle\Repository;

/**
 * lafemmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lafemmeRepository extends \Doctrine\ORM\EntityRepository
{
}
